#ifndef HTTP_SERVER_UTIL_ERRCODE_ERRCODE_H_
#define HTTP_SERVER_UTIL_ERRCODE_ERRCODE_H_

#define HTTP_SERVER_ERR_OK 0
#define HTTP_SERVER_ERR_SOCKET_OPEN 1
#define HTTP_SERVER_ERR_SOCKET_BIND 2
#define HTTP_SERVER_ERR_NULL_PTR 3
#define HTTP_SERVER_ERR_SOCKET_LISTEN 4
#define HTTP_SERVER_ERR_THREAD_CREATE 5
#define HTTP_SERVER_ERR_THREAD_DETACH 6
#define HTTP_SERVER_ERR_SOCKET_SET_OPT 7

extern const char *http_server_errcode_lookup[8];

#endif
