#include "errcode.h"

const char *http_server_errcode_lookup[8] = {
    "HTTP_SERVER_ERR_OK",
    "HTTP_SERVER_ERR_SOCKET_OPEN",
    "HTTP_SERVER_ERR_SOCKET_BIND",
    "HTTP_SERVER_ERR_NULL_PTR",
    "HTTP_SERVER_ERR_SOCKET_LISTEN",
    "HTTP_SERVER_ERR_THREAD_CREATE",
    "HTTP_SERVER_ERR_THREAD_DETACH",
    "HTTP_SERVER_ERR_SOCKET_SET_OPT",
};
